### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by xavierfontaine** [Hongyuy/sbrl#6]
There happens to be a memory leak issue. I have experienced it through the R wrapper on Windows, but I believe the issue is more general and relates to the C implementation itself.

The issue is described at length [on StackOverflow](https://stackoverflow.com/questions/51324870/memory-leak-and-c-wrapper), with a minimal reproducible example.
An SO user has provided [further evidences](https://stackoverflow.com/questions/51324870/memory-leak-and-c-wrapper#comment89628797_51324870) of a memory leak, in reply to my post.

**Comment by Hongyuy** [comment]
> There happens to be a memory leak issue. I have experienced it through the R wrapper on Windows, but I believe the issue is more general and relates to the C implementation itself.
> 
> The issue is described at length [on StackOverflow](https://stackoverflow.com/questions/51324870/memory-leak-and-c-wrapper), with a minimal reproducible example. An SO user has provided [further evidences](https://stackoverflow.com/questions/51324870/memory-leak-and-c-wrapper#comment89628797_51324870) of a memory leak, in reply to my post.

A late fix and reply. The memory leak issue is fixed in the latest sbrl package.
see https://cran.r-project.org/web/checks/check_results_sbrl.html
