### ISSUE TITLE
how install this on Windows?

### ISSUE THREAD

**Issue by Sandy4321** [Hongyuy/sbrl#7]
is it on cran?
how install this?
how different this from CORELS?

**Comment by Hongyuy** [comment]
It is on CRAN. 
To install it on windows, you will need header files from GMP and GSL. You can download them here, https://www.stats.ox.ac.uk/pub/Rtools/libs.html. 
If you put the uncompressed files under C:\Rtools\local323, which is the default location to look at under Windows, you should be able to directly install SBRL from source (download the source here https://cran.r-project.org/web/packages/sbrl/index.html). The source code on CRAN is however, before merging the memory leak issue.

**Comment by Sandy4321** [comment]
Great, so from where to get correct code with memory leak issue resolved?

**Comment by Hongyuy** [comment]
> Great, so from where to get correct code with memory leak issue resolved?

this is a late reply, but I eventually completely solved the memory leak issue and converted the code into C++. The latest cran check results for sbrl is pretty clean now. https://cran.r-project.org/web/checks/check_results_sbrl.html
